<#
.SYNOPSIS
    Install the "cft" command so CallFromTwitch can be driven from any prompt.

.DESCRIPTION
    Puts a small shim on the user's PATH that forwards to cft.cmd in this repo.
    A shim rather than a copy: the repo stays the single source of truth, so a
    git pull updates the tool with no reinstall.

    Run from the repo:            .\install.ps1
    Or in one line from a clone:  irm <raw-url>/install.ps1 | iex

.NOTES
    Everything is per-user (HKCU + %LOCALAPPDATA%); no admin rights needed.
#>
[CmdletBinding()]
param(
    # Where the shim goes. The default is already on PATH for most setups.
    [string]$BinDir = "$env:LOCALAPPDATA\Programs\CallFromTwitch",
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$esc = [char]27
$green = "$esc[92m"; $red = "$esc[91m"; $yellow = "$esc[93m"
$dim = "$esc[90m"; $white = "$esc[97m"; $reset = "$esc[0m"
if ($env:CFT_NO_COLOR) { $green = $red = $yellow = $dim = $white = $reset = '' }

# $PSScriptRoot is empty when this file is piped through iex rather than run
# as a file. That cannot work - the shim needs a real repo path - so say so
# plainly instead of failing later on an empty-string argument.
$repo = $PSScriptRoot
if (-not $repo) {
    Write-Host ""
    Write-Host "$red  ! install.ps1 must be run as a file, not piped into iex.$reset"
    Write-Host ""
    Write-Host "  To install from scratch, use bootstrap.ps1 instead:"
    Write-Host "    irm https://raw.githubusercontent.com/sruckstar/CallFromTwitch/main/bootstrap.ps1 | iex"
    Write-Host ""
    Write-Host "  Or, in an existing clone:  .\install.ps1"
    Write-Host ""
    exit 1
}
$target = Join-Path $repo 'cft.cmd'
$shim = Join-Path $BinDir 'cft.cmd'

if ($Uninstall) {
    if (Test-Path $shim) { Remove-Item $shim -Force }
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    if ($userPath -and $userPath.Split(';') -contains $BinDir) {
        $kept = $userPath.Split(';') | Where-Object { $_ -and $_ -ne $BinDir }
        [Environment]::SetEnvironmentVariable('Path', ($kept -join ';'), 'User')
    }
    # The shim's only other footprint.
    [Environment]::SetEnvironmentVariable('CALLFROMTWITCH_ROOT', $null, 'User')
    Write-Host ''
    Write-Host "$green  Removed the 'cft' command.$reset"
    Write-Host "$dim  The repo and the voice server are untouched.$reset"
    Write-Host ''
    exit 0
}

if (-not (Test-Path $target)) {
    Write-Host "$red  cft.cmd not found next to this script.$reset"
    Write-Host "$dim  Run install.ps1 from inside the CallFromTwitch repo.$reset"
    exit 1
}

& (Join-Path $repo 'voice_server\_banner.ps1') 'Command-line setup'

New-Item -ItemType Directory -Path $BinDir -Force | Out-Null

# A one-line forwarder. %* passes the arguments through, and the exit code of
# the real script becomes this one's, so "cft install && cft start" behaves.
# The shim is deliberately pure ASCII. cmd tracks its position in a batch file
# by byte offset, so the `chcp 65001` inside cft.cmd re-decodes the shim's
# remaining bytes; a non-ASCII repo path (e.g. a folder named in Cyrillic)
# written inline would be cut mid-character and the call would fail. The path
# therefore travels in an environment variable, stored as Unicode by Windows
# and never re-decoded by cmd.
[Environment]::SetEnvironmentVariable('CALLFROMTWITCH_ROOT', $repo, 'User')
$env:CALLFROMTWITCH_ROOT = $repo

$shimBody = @'
@echo off
REM Generated by install.ps1 - forwards to the CallFromTwitch repo.
REM The repo path lives in CALLFROMTWITCH_ROOT (set by install.ps1) so this file
REM can stay pure ASCII; see the note in install.ps1 for why that matters.
if not defined CALLFROMTWITCH_ROOT (
    echo CallFromTwitch is not set up. Run install.ps1 from the repo again.
    exit /b 1
)
if not exist "%CALLFROMTWITCH_ROOT%\cft.cmd" (
    echo Repo not found at "%CALLFROMTWITCH_ROOT%".
    echo Run install.ps1 from the repo again, or move it back.
    exit /b 1
)
call "%CALLFROMTWITCH_ROOT%\cft.cmd" %*
exit /b %ERRORLEVEL%
'@

[System.IO.File]::WriteAllText($shim, $shimBody, (New-Object System.Text.ASCIIEncoding))

Write-Host "  Installed:  $shim"
Write-Host "$dim  Forwards to: $target$reset"

# Add to the user PATH only when it is genuinely absent, so repeat runs do not
# grow the variable.
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$entries = if ($userPath) { $userPath.Split(';') | Where-Object { $_ } } else { @() }
if ($entries -notcontains $BinDir) {
    [Environment]::SetEnvironmentVariable('Path', (($entries + $BinDir) -join ';'), 'User')
    # The current process keeps its own copy of PATH, so make this shell work too.
    $env:Path = "$env:Path;$BinDir"
    Write-Host "$yellow  Added $BinDir to your PATH.$reset"
    Write-Host "$dim  Open a new terminal for it to take effect everywhere.$reset"
} else {
    $env:Path = "$env:Path;$BinDir"
    Write-Host "$dim  $BinDir was already on your PATH.$reset"
}

Write-Host ''
Write-Host "$white  Ready. From any folder:$reset"
Write-Host ''
Write-Host "    cft install     $dim set up the voice server$reset"
Write-Host "    cft start       $dim run it$reset"
Write-Host "    cft status      $dim check what is installed$reset"
Write-Host ''
Write-Host "$dim  Remove the command again with:  .\install.ps1 -Uninstall$reset"
Write-Host ''
